spring:
  application:
    name: zookeeper-consumer-service-demo
  cloud:
    zookeeper:
      dependencies:
        zookeeper-backend-service-demo:
          path: /zookeeper-backend-service-demo
          loadBalancerType: ROUND_ROBIN
          required: false
      default-health-endpoint: /actuator/health
  devtools:
    add-properties: false
management:
  endpoint:
    refresh:
      enabled: true
ribbon:
  filter:
    metadata:
      enabled: true
backend-service-name: zookeeper-backend-service-demo
zookeeper-backend-service-demo:
  ribbon:
    NFLoadBalancerRuleClassName: com.bkhatkov.zookeeperconsumerservicedemo.ribbon.metadata.MetadataAwareRule