spring:
  application:
    name: zookeeper-consumer-service-demo
  cloud:
    zookeeper:
      dependencies:
        zookeeper-dependency-demo:
          path: /zookeeper-backend-service-demo
          loadBalancerType: STICKY
          required: false
      default-health-endpoint: /actuator/health
management:
  endpoint:
    refresh:
      enabled: true
server:
  port: 8080